# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_auto_20181029_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicle',
        ),
    ]
