# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_auto_20181104_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='own',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='own',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
