# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_auto_20181104_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own',
            name='city',
            field=models.CharField(default='Mendoza', max_length=150),
        ),
    ]
