# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_auto_20181104_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_date',
        ),
        migrations.AddField(
            model_name='own',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complain',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Own'),
        ),
        migrations.AddField(
            model_name='complain',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Vehicle'),
        ),
    ]
